version: 0.0
os: linux
files:
  - source: imagedefinitions.json
    destination: /tmp/

hooks:
  BeforeInstall:
    - location: scripts/stop_containers.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_containers.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
