version: 0.0
os: linux
files:
  - source: dist/my-angular-project
    destination: /var/www/my-angular-project
permissions:
  - object: /var/www/my-angular-project
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: scripts/stop_containers.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_containers.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
      
